# Generated by Django 4.2.6 on 2023-10-07 07:15

import FirstProject.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citie',
            fields=[
                ('name', models.CharField(help_text='Введите название города', max_length=100, primary_key=True, serialize=False, verbose_name='Город')),
                ('date_of_foundation', models.DateField(help_text='Введите дату основания города', verbose_name='Дата основания')),
                ('population', FirstProject.models.IntegerRangeField(help_text='Введите количество жителей страны', verbose_name='Население')),
            ],
            options={
                'db_table': 'Citie',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('name', models.CharField(help_text='Введите фамилию и инициалы основателя', max_length=100, primary_key=True, serialize=False, verbose_name='Основатель')),
                ('year_of_birth', models.DateField(help_text='Введите дату рождения основателя', verbose_name='Год рождения')),
                ('brief_biography', models.TextField(verbose_name='Краткая биография')),
            ],
            options={
                'db_table': 'Founder',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(help_text='Введите название языка', max_length=100, primary_key=True, serialize=False, verbose_name='Язык')),
                ('number_of_speakers', FirstProject.models.IntegerRangeField(help_text='Введите количество людей, говорящих на этом языке', verbose_name='Число говорящих')),
                ('count_of_symbols', FirstProject.models.IntegerRangeField(help_text='Введите количество символов в алфавите', verbose_name='Алфавит')),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя', max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите фамилию', max_length=50, null=True, verbose_name='Фамилия')),
                ('city', models.ForeignKey(blank=True, help_text='Введите родной город жителя', null=True, on_delete=django.db.models.deletion.CASCADE, to='FirstProject.citie', verbose_name='Родной город')),
                ('id_user', models.ForeignKey(blank=True, help_text='Выберите id жителя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id жителя')),
            ],
            options={
                'db_table': 'Resident',
            },
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('name', models.CharField(help_text='Введите название страны', max_length=100, primary_key=True, serialize=False, verbose_name='Страна')),
                ('capital', models.CharField(help_text='Введите столицу этой страны', max_length=50, verbose_name='Столица')),
                ('area', FirstProject.models.IntegerRangeField(help_text='Введите площадь страны', verbose_name='Площадь')),
                ('language', models.ForeignKey(help_text='Введите название языка', on_delete=django.db.models.deletion.CASCADE, to='FirstProject.language', verbose_name='Национальный язык')),
            ],
            options={
                'db_table': 'Countrie',
            },
        ),
        migrations.AddField(
            model_name='citie',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Введите название страны, в которой находится этот город', on_delete=django.db.models.deletion.CASCADE, to='FirstProject.countrie', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='citie',
            name='founder',
            field=models.ForeignKey(help_text='Введите основателя города', on_delete=django.db.models.deletion.CASCADE, to='FirstProject.founder', verbose_name='Имя основателя'),
        ),
    ]
