# Generated by Django 4.2.6 on 2023-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0003_housing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
