# Generated by Django 4.2.6 on 2023-11-21 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FirstProject', '0004_alter_resident_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citie',
            table=None,
        ),
        migrations.CreateModel(
            name='Authoritie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя', max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите фамилию', max_length=50, null=True, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('city', models.ManyToManyField(to='FirstProject.citie')),
                ('id_user', models.ForeignKey(blank=True, help_text='Выберите id представителя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id представителя власти')),
            ],
            options={
                'db_table': 'Citie',
            },
        ),
    ]
