# Generated by Django 4.2.6 on 2023-11-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0005_alter_citie_table_authoritie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authoritie',
            table=None,
        ),
        migrations.AlterModelTable(
            name='citie',
            table='Citie',
        ),
    ]
