# Generated by Django 4.2.6 on 2023-11-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0006_alter_authoritie_table_alter_citie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authoritie',
            table='Authoritie',
        ),
    ]
