# Generated by Django 4.2.6 on 2023-11-21 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FirstProject', '0007_alter_authoritie_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='citie',
            name='power_id',
            field=models.ForeignKey(blank=True, help_text='Выберите id представителя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id представителя власти'),
        ),
    ]
