# Generated by Django 4.2.6 on 2023-12-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0008_citie_power_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(help_text='Введите район города', max_length=100, primary_key=True, serialize=False, verbose_name='Район')),
                ('authoritie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstProject.authoritie', verbose_name='Представитель власти')),
                ('city', models.ManyToManyField(to='FirstProject.citie')),
            ],
        ),
    ]
