# Generated by Django 4.2.6 on 2023-12-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0009_district'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='District',
        ),
    ]
