# Generated by Django 4.2.6 on 2023-12-11 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FirstProject', '0011_remove_authoritie_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authoritie',
            new_name='Government',
        ),
        migrations.RenameField(
            model_name='citie',
            old_name='name',
            new_name='name_city',
        ),
        migrations.AlterModelTable(
            name='government',
            table='Government',
        ),
    ]
