# Generated by Django 4.2.5 on 2023-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0012_rename_authoritie_government_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, help_text='Введите район города', max_length=100, null=True, verbose_name='Район'),
        ),
    ]
